### PR TITLE
Pascals-triangle: add exercise

### PR DESCRIPTION
**Pull request by filiptoskovic**
Config.json is missing

### CODE REVIEW

**Comment by rpottsoh** [comment]
This looks good so far.  How did you create the README?

Take a look at exercism/problem-specifications#1341.  I will be merging that PR maybe this evening (my time).  If you review what I plan to merge you can get a head start and make those changes to your code now.

I'll get the config.json updated later, hopefully by this evening.

**Comment by filiptoskovic** [comment]
I had to make a little workaround to create readme.  I put problem-specifications in exercism directory.

**Comment by rpottsoh** [comment]
it is better to keep all exercism repos with a single folder.  I have a folder called exercism and within it I have Delphi, CSharp, and problem-specifications etc.  If you folder names are the same as the original repo name configlet will find what it needs.  If you have changed the folder names (like I have) then you need to use the `-p` command line switch.

when I am in my exercism-delphi folder I must:
```
configlet generate . -p ..\exercism-problem-specifications
```
in order to generate all the READMEs for Delphi.

Until today I assumed that configlet was parsing config.json to determine which exercises to make READMEs for.  You have shown me that it is simply traversing the exercises folder in each of the two repos and generating READMEs for folders that match.

**Comment by rpottsoh** [comment]
I am going to go ahead and merge this.

**Comment by rpottsoh** [comment]
You will want to delete the branch and do a FF pull from exercism master to local master.  Then push to origin master.

**Comment by filiptoskovic** [comment]
Ok. I ll work on OCR numbers now

**Pull request merged**
