### PR TITLE
gigasecond: add new exercise

### PR DESCRIPTION
**Pull request by filiptoskovic**

### CODE REVIEW

**Comment by rpottsoh** [comment]
It kind of feels like you skimped out on the example.  Honestly though I am fine with it, it is just an example.  I didn't know about those functions that you used anyway, I learned something  :smile: 

If you are done I will merge, just let me know.  This looks fine to me.  Thanks a lot!

**Comment by filiptoskovic** [comment]
I agree. These functions were best match, but it can't omit miliseconds, so I used WD40 and duct tape. And one thing more, when I squash commits git creates branch and merge, so I have left 3 commits.

**Comment by rpottsoh** [comment]
I squash when I merge.  When you squash commits with GK it will do it to
local.  You then have to push to origin.  GK will want you to force push
and you will have to click the red force push button two times, then origin
will look like local.  It is usually better not to squash until the very
end.  It is easier to see the progression of changes.

**Comment by filiptoskovic** [comment]
OK, in that case I will  leave it. But these are not real changes, I forgot to comment ignore, or to rename example and like that.

**Pull request merged**
