### PR TITLE
Changes based on instructions from PR #135

### PR DESCRIPTION
**Pull request by rpottsoh**
ref: #135

### CODE REVIEW

**Comment by kytrinyx** [comment]
@iHiD: this is the first track to implement core exercises! ✨  Do you have any thoughts about structure, etc?

@rpottsoh I don't know a lot about how this will play out, so take anything I say as musings rather than directions or recommendations. My first thought when seeing this is that I think it would be valuable to have at least 2 or three side exercises for each core exercise. I don't know if I'd prefer to have fewer core exercises for now, and then expand both in terms of core and non-core exercises as you add more, or perhaps only have more side exercises for the first core exercises.

I suppose one question I have is whether or not you think that exercises that you add later will be easier or harder than the ones that you already have. If they're more difficult, then you'll probably want to allow for expansion to the core set.

Like I said... I don't really know.

**Comment by kytrinyx** [comment]
> Should the side exercises "daisy-chain" from the core exercise or should each of the sides be unlocked by the same core exercise?

Each of the sides can be unlocked by the same core exercise. This will mean that once they finish the core exercise, they can choose which of the side exercises to implement, and in which order.

> I think expansion will be necessary.

In that case I think I'd recommend starting with fewer core exercises, and adding more as you go.

> I am working on an exercise that will be unique to this track

Fun! On our side it doesn't matter whether you make this a core exercise or not—it's really up to you to place it where you think it will do the most good.

**Comment by rpottsoh** [comment]
Thanks for the explanation and suggestion.  Seems to me if an exercise has no exercises unlocked by it then it doesn't need to be a core exercise.  Later, it could become a core exercise if some other exercise (likely a new exercise) made sense to be unlocked by it.

**Comment by kytrinyx** [comment]
> Seems to me if an exercise has no exercises unlocked by it then it doesn't need to be a core exercise.

That's one way of looking at it. Another would be that a _core exercise_ should teach you something meaningful about the language (as opposed to give you a way to practice things you've already been introduced to). I'm not sure either of these is the definitive "right answer".

**Comment by rpottsoh** [comment]
Agreed.  Thanks for reviewing.

**Pull request merged**
