### PR TITLE
Matrix: add new exercise to delphi track

### PR DESCRIPTION
**Pull request by filiptoskovic**
Readme added after numerous fries and fails

### CODE REVIEW

**Comment by rpottsoh** [comment]
Nice work.  Yes, you have a bunch of extra commits.  For starting out it isn't a big deal.  We can fix that.  I use to do it all the time too while I was trying to figure things out.

I can squash the commits when I merge or if you would like, you can try squashing the commits yourself.  All the commits are compressed into a single commit which then have to force push back to origin.  The PR will the only show there being 1 commit that contains all of the changes that make of the exercise.  All the minor/messed up commits will vanish.  Nice way to tidy up when it isn't necessary to keep every commit.

**Comment by rpottsoh** [comment]
I cleaned up the other commits, that appeared to be for another exercise.  The key to having this work is to have the branch checked out for the exercise you are working on.  If you decide to work on a different exercise you need to checkout another branch for that exercise.  If you don't have a branch already created you need to checkout master then create the new branch.  You want your branches to branch off of master and not each other, because they can.

**Comment by rpottsoh** [comment]
you are merging.  You will not be merging.  For the sake of what we are working on here.  If you find yourself merging you should stop.  As you make changes you will want to commit those changes and then push those changes to Origin (your fork).  Everything will still be in the matrix branch.  You never merge.  Nothing gets back to master until the PR is merged.

**Comment by filiptoskovic** [comment]
Ok, that is "basic concept I have misunderstood". Whole time I'm trying to merge. So I don't need to merge.

**Comment by filiptoskovic** [comment]
I think that Pascal triangle will be much smoother. Delphi is easy, Exercism and configlet are fine, but this Git... Whole day I'm looking tutorials. Thank you.

**Comment by rpottsoh** [comment]
You tried merging branch matrix back to your master again.  I am going to go ahead and merge this PR and we can try anew with pascals-triangle if that is what you are working on next.

**Pull request merged**
