### PR TITLE
RNA-Transcription: Add invalid input

### PR DESCRIPTION
**Pull request by amoradell**
Test with invalid input raises exception

### CODE REVIEW

**Comment by rpottsoh** [comment]
@amoradell I don't think I want to make these changes.  I would like to keep the exercise in sync with the exercise as it is described in problem-specifications.  Furthermore efforts were made to remove tests on bad input as they have been deemed to be unrelated to solving the problem at hand.  PR exercism/problem-specifications#1027 removed tests for bad input.

**Comment by amoradell** [comment]
Ok, it's more consistent with problem specifications. It's just that other tracks test invalid inputs and expect error correctly handled. I changed my comment on Zorica exercise.

**Comment by rpottsoh** [comment]
The current trend is to not spend energy testing for bad input.  In a production environment typically upstream code would take care of making sure the input was proper before handing the data off to be processed.  Unless the exercises focus is on detecting bad input the main goal of the exercise shouldn't be encumbered with dealing with bad input.  Many tracks are slow to update their implementations and others just choose to not follow the canonical data.

**Comment by amoradell** [comment]
It's better to find edge cases, I think.

**Comment by rpottsoh** [comment]
If the input is valid then it can be useful to find edge cases where the algorithm doesn't properly process the valid input.

**Pull request closed without merging**
